### ISSUE TITLE
Remove step 5 in the readme instructions

### ISSUE THREAD

**Issue by waldyrious** [OSAS/strapping-mediawiki#1]
Why disable anonymous editing? is that something specifically needed to use this skin? If not, that line would perhaps be better placed in elsewhere, perhaps in the Customization section.

**Comment by quaid** [comment]
Conceptually, this skin hides that it is a MediaWiki site - that was part of the original design intention. Disabling anonymous editing makes the [edit] link go away, which was identified as distracting and detracting from the visual quality of the site. It's also true that the original target, www.ovirt.org, does not have an anonymous-editable wiki, so the two design intentions match.

It could certainly be identified as optional or a customization, but we probably want to include a statement on the design intention for the customization.

**Comment by waldyrious** [comment]
I see. in that case, I would suggest indeed marking the step 5 as optional, mentioning the rationale behind that setting. In fact, perhaps marking it as 4.b would make more sense, too. If you have no objections, I can send a pull request with a suggested rewording.

Furthermore, it could even be more interesting to not disable anonymous editing, and instead tweak the display of the edit link, so it is more discrete, and says something like "suggest changes". This, coupled with the [FlaggedRevs](https://www.mediawiki.org/wiki/Extension:FlaggedRevs) extension (so that all edits are moderated before going live), would make the site more open and dynamic without any risk of it displaying vandalism or spam to unsuspecting visitors. How about testing this for the www.ovirt.org site? It could be an interesting experiment :)

**Comment by quaid** [comment]
Very interesting idea. I like lowering barriers as much as possible, within reason for each project. This is an interesting way to get all the way to true anonymity without compromising the site integrity. It would require a bit more MediaWiki-style discipline - I bet the revisions-to-be-checked queue is web-based by default and doesn't issue an email to the editors group?

I opened a new ticket suggesting this; I think this is something we can look at doing after we've settled down some other open infrastructure items, unless we get a MediaWiki guru who wants to come along and help us make this happen sooner. ;-D

https://fedorahosted.org/ovirt/ticket/33

**Comment by garrett** [comment]
True; it should be optional. If I remember clearly, I quickly wrote the docs late on a Friday evening, right before signing off. I'm sure there are other oversights.

It should be optional, as the theme works well as a normal wiki too (and not just in "wiki as a website" mode).

@quaid is correct in that it was originally designed for presenting a standard website to end-users, yet allowing many authors to edit it as a wiki-powered community CMS (essentially).

As we go forward, I think we want to make sure both audiences (wiki-powered-website and freely editable community wiki) are addressed.

I've just edited the file, changing the steps and adding a subsection for optional configuration.

**Comment by waldyrious** [comment]
@quaid that's great. I'll make some experiments locally and will report back regarding implementation details :) I really don't think it would be hard :D

**Comment by waldyrious** [comment]
@quaid, @garrett -- can you (or someone you can ping) comment on the changes I proposed on [that ticket](https://fedorahosted.org/ovirt/ticket/33)?

**Comment by quaid** [comment]
OK, just replied on the ticket, and this thread here reminded of @waldir's motivation. This matches what @dneary and I have talked about for moving toward near-anonymous or anonymous-with-moderation.

I'll take this to the oVirt Infra team for review, it might be the perfect thing for one of the journeyfolk team members to add.
