### ISSUE TITLE
undefined variable & index

### ISSUE THREAD

**Issue by waldyrious** [OSAS/strapping-mediawiki#2]
I'm seeing the following warnings from PHP after doing a vanilla installation (i.e. following the steps from the README):

> **Notice**: Undefined index: view in **/var/www/mw-dev/skins/strapping/Strapping.php** on line **217**
> 
> **Notice**: Undefined variable: options in **/var/www/mw-dev/skins/strapping/Strapping.php** on line **221**
> 
> **Notice**: Undefined index: login in **/var/www/mw-dev/skins/strapping/Strapping.php** on line **361**

**Comment by waldyrious** [comment]
More warnings after logging in:

> **Notice**:  Undefined variable: theImg in **/var/www/mw-dev/skins/strapping/Strapping.php** on line **662**
> 
> **Warning**: Missing argument 1 for StrappingTemplate::renderPortals(), called in /var/www/mw-dev/skins/strapping/Strapping.php on line 335 and defined in **/var/www/mw-dev/skins/strapping/Strapping.php** on line **406**

**Comment by garrett** [comment]
Verified fixed here. Thanks for the pull request, @waldir!
