### ISSUE TITLE
Question about drop-in themes

### ISSUE THREAD

**Issue by AlJohnson** [OSAS/strapping-mediawiki#20]
Could I ask a question about using some of the bootstrap themes?  I purchased this one: https://wrapbootstrap.com/theme/citypress-responsive-blog-WB052C9L0
and tried to just drop it in place of the bootstrap dir and it didn't work.  Do you know if it will take considerable effort to get those to work? 

Thanks,
Al

**Comment by garrett** [comment]
It shouldn't be too hard to get things to work, I would guess. The correct HTML elements need proper classes.

I am using many bootstrap classes throughout the theme, so the theme should probably show up in some form.

Random semi-related thought: It may make sense to check for a custom `header.php` and/or `footer.php` and use those if they exist. (We could have `header-example.php` and `footer-example.php` for easy copying/renaming.)

Ideally, I'd like to re-use MediaWiki framework whenever possible, but in some cases it may be easier to have drop-in support.

**Comment by garrett** [comment]
Could you share a screenshot here of what it looks like with the theme applied? It could help to demonstrate how much work might be needed. (Even if there's "a lot", it probably really isn't all too much — just a bit of classes, most likely, and possibly that custom header/footer support.)

**Comment by AlJohnson** [comment]
Hi Garrett, the page looked just like it did with the previous Chrome-Vector issue.  But, I've abandoned that theme and went with the free Cosmo that has worked out pretty well.  Thanks, al
