### ISSUE TITLE
Responsive layouts not working in Chrome and IE

### ISSUE THREAD

**Issue by AlJohnson** [OSAS/strapping-mediawiki#24]
Chrome v13.0.782.220 m
IE v9.0.8112

I don't know if this is an issue with the theme or just the browsers, but these two browsers don't change their layouts with respect to the menu bar (Main Page, Community Portal, Current Events, etc.) when the width of the browser page changes.  Looks like the main container that's not responding is affecting other parts of the page that uses the same container (like the "edit" links to the upper right of each section).

Demo at: 
http://ec2-50-112-91-143.us-west-2.compute.amazonaws.com/wiki/index.php/Main_Page

Thank you

**Comment by AlJohnson** [comment]
FYI, it works more-or-less in Opera and FF.

**Comment by garrett** [comment]
This used to work in an older version of the theme. 

I can confirm that it is currently working in recent Firefox and Chrome, but does not work in IE (even IE10). I'm investigating this today.

**Comment by garrett** [comment]
After lots of debugging _everything_, I've finally traced it down to a broken implementation of MediaWiki ResourceLoader and the way it handles media queries (or doesn't, properly, that is). I have a work-around fix landing in the repo shortly.
