### ISSUE TITLE
"Username" input is not properly styled

### ISSUE THREAD

**Issue by wilkinson** [OSAS/strapping-mediawiki#25]
The "Username" input is not styled by Bootstrap at all, but the "Password" input element _is_ styled by Bootstrap. It looks a little weird to me to click to the next element and see a different shade of blue highlighting it!

I'm using Chrome 26 on a Mac, but I also see this problem in Firefox 20, Safari 6.0.4, and Opera 12.15.

![username](https://f.cloud.github.com/assets/437277/456936/d7e29148-b37e-11e2-9d7f-d4b0752524a9.png)
![password](https://f.cloud.github.com/assets/437277/456937/da59559c-b37e-11e2-8fef-004df31aa141.png)

**Comment by garrett** [comment]
Thanks for pointing out this issue!

While it would seem simple to fix, it's actually a bit trickier as Bootstrap is styling `input[type="text"], input[type="password"]`, etc. and MediaWiki only specifies a type for the password box, not the username.

As Bootstrap doesn't want to accidentally make it look like a button, it apparently does not style non-typed inputs.

While it would be the correct fix, I'd rather not patch MediaWiki or augment Bootstrap in the theme itself. We can send patches upstream, sure, but the theme shouldn't have to depend on the fixed version or forcing the person who uses the theme to apply a patch themselves.

The best (but not ideal) solution here would probably be to duplicate the style of Bootstrap for generic input boxes in screen.css (and then push it upstream).

I'll work on a fix this week.

**Comment by waldyrious** [comment]
off-topic: it would be amusing to see a patch by [garrett](http://github.com/garrett) in Wikimedia's [gerrit](http://gerrit.wikimedia.org) :P (Now imagine if they had adopted [gareth](https://github.com/dantman/gareth)!)

**Comment by waldyrious** [comment]
For completeness/future reference, please add a link here to the upstream patch once that's done.
