### ISSUE TITLE
Mention origins of the skin in readme

### ISSUE THREAD

**Issue by waldyrious** [OSAS/strapping-mediawiki#3]
The README file should include a link to http://www.ovirt.org as the original home of the skin (as a bonus, the link would double as a demo of a customized instance of Strapping) and perhaps http://blogs.gnome.org/bolsh/2013/01/18/awesome-mediawiki-theme, for reference (or at least the README itself should include similar text directly).

**Comment by garrett** [comment]
Thanks for the suggestion! Added!
