### ISSUE TITLE
Sidebar disappeared after the newest update

### ISSUE THREAD

**Issue by threadflow** [OSAS/strapping-mediawiki#34]

**Comment by garrett** [comment]
Can you elaborate or provide a screenshot please?

Thanks!

**Comment by threadflow** [comment]
I thought in the recent commit 1d2e2d241fde0f417726117360a73404cea461c2, line 676 in file `Strapping.skin.php` should be change from `!$content` to `!isset($content)`. Current code is `isset($content)`.

**Comment by garrett** [comment]
Thanks for the catch. It still works normally for me; I guess it's because the content of our `MediaWiki:Sidebar`s differ. I'll commit and push up the change now.

**Comment by garrett** [comment]
I'm guessing this is fixed now? Please reopen if it's not working for you. Thanks! (:
