### ISSUE TITLE
Use ResourceLoader

### ISSUE THREAD

**Issue by Krinkle** [OSAS/strapping-mediawiki#46]
Loading js and css files directly from the output handler has been deprecated since MediaWiki 1.17 with the introduction of ResourceLoader.

Consider using it so that this skin will make automatically make use of those performance improvements (such as combined and minified css/js, as well as automatic combining of images in the css request) and integrates better with current practices.

---
- [ResourceLoader](https://www.mediawiki.org/wiki/ResourceLoader)

**Comment by garrett** [comment]
The skin was using ResourceLoader at one point, but we had to revert as ResourceLoader is broken and does not handle media queries properly.

I would be happy if we could switch back, but we simply cannot until ResourceLoader is fixed (or if someone finds a usable work-around).

**Comment by Krinkle** [comment]
Ah, indeed. It did use it in the past, but reverted in 3e1a00c75852dd4a435be55e17823f721e275ffb.

Though it could indeed be a bug, I suspect it might be a misunderstanding of the "media" property in the module registry (and the way we treat it). It can be confusing, and I've seen others run into the same thing but I'm pretty sure this will work and doesn't require you to give up any functionality or queries.

I don't have a perfect solution, but in the interest of getting things done here's what I recommend you do to work around it.

First, this is why it fails:
- Browsers don't support nested `@media` blocks. <small>(though there is some movement towards allowing nested media queries in CSS3 and CSS4, it's still far away and wouldn't apply to older browsers for the traditional "screen" and "print" kind of media query.)</small><br/>Example demo: http://jsfiddle.net/j4A2h/light/<br/>Browser support: http://www.browserstack.com/screenshots/c68ad86f7263aa4a7197e2f3f270641921c29bc2
- You're currently using `@media` blocks in css while also specifying `"media" => "screen"` on the individual files of the module.
- Though browsers don't support nested media queries, they give you 1 extra free level if you use raw `<style>` or `<link>` because those tags can have a media attribute.
- ResourceLoader combines and minifies individual files and modules in a single request, so the separation is purely organisational. Since you explicitly specify `"media"` on each file in the module, ResourceLoader has to put a `@media` block around that css to preserve that query.
- The result is that the `@media` inside the css ends up inside the implicitly created `@media (screen)` block you declared with `"media" => "screen"`. And though ResourceLoader doesn't touch yours, browsers don't support nested queries – as we've found out.

Though it is annoying we loose that extra free level, it isn't a side effect of ResourceLoader's complexity (the same would happen if you manually concatenate files).

This has been reported as [bug 46933](https://bugzilla.wikimedia.org/show_bug.cgi?id=46933). It could parse the media attributes and wrap files and try and merge media queries, but that's not something we're working on at the moment (patches welcome though).

To work around it make sure you don't set `"media"` on files that also use `@media` inside a file. Either:
- Move the `@media` blocks in separate files (and don't set `"media"` on those)
- Remove the `"media" => "screen"` settings in the module definition you have now. If you care for everything being "screen", do so explicitly inside your stylesheets, and be sure not to accidentally nest them, just like you normally would in CSS.

**Comment by ebraminio** [comment]
IMO this is a most need for this great theme. [ResourceLoader](http://www.mediawiki.org/wiki/ResourceLoader/Features) has a lot feature that for me [this](http://www.mediawiki.org/wiki/ResourceLoader/Features#Flipping) is one of its best, supporting RTL style.

**Comment by ebraminio** [comment]
Also as [MediaWiki 1.22](http://www.mediawiki.org/wiki/Manual:Coding_conventions/CSS#Less), MediaWiki has LESS parsing ability that I think it can be easily used with Bootstrap Less styles.

**Comment by Krinkle** [comment]
You probably shouldn't register Bootstrap's raw Less files though. Use the release files they provide and register them as regular css file(s). This prevents conflicts with regards to the implementation, version and configuration of Lessjs and Lessphp.
