### ISSUE TITLE
all menus folded out

### ISSUE THREAD

**Issue by adrelanos** [OSAS/strapping-mediawiki#53]
All menus are folded out by default. Also happens when no extensions are enabled. See screenshot.

![screen shot](http://oi57.tinypic.com/1588n03.jpg)

How to fix that?

**Comment by garrett** [comment]
Please check https://github.com/OSAS/strapping-mediawiki/issues/39#issuecomment-22057027

**TL;DR**: It's probably one of these two things:
1. Upgrade your version of MediaWiki. It's old. Old versions of MediaWiki use very old, incompatible versions of jQuery.
2. Your hosting provider might be a cheap one that injects additional JavaScript that breaks things. If so (and it's not just old versions of MediaWiki), then you'd have to either switch providers or ask them to stop injecting stuff.

Please reopen this bug if it is not related to issue #39 or not one of the 2 above issues. Thanks!

**Comment by adrelanos** [comment]
It was our MediaWiki:Common.css that caused this. Thank you for your help.
